linters:
  Indentation:
    enabled: true
  PropertySortOrder:
    enabled: false
  SelectorDepth:
    enabled: false
  CapitalizationInSelector:
    enabled: false
  Comment:
    enabled: false
  QualifyingElement:
    allow_element_with_attribute: true
