linters:
  Indentation:
    enabled: true
  PropertySortOrder:
    enabled: false
  SelectorDepth:
    enabled: false
  SelectorFormat:
    enable: false
  CapitalizationInSelector:
    enabled: false
  Comment:
    enabled: false
  QualifyingElement:
    allow_element_with_attribute: true
  NameFormat:
    enabled: false
  PlaceholderInExtend:
    enabled: false
