language: node_js
node_js:
  - "6.6.0"
before_install:
  - rvm install 2.2.5
install:
  - npm install
before_script:
  - node_modules/gulp/bin/gulp.js build
script:
  - node_modules/gulp/bin/gulp.js test
